In [1]:
!pip install tensorflow # installing  tensorflow to the google collab. It will copy the files and install.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import tensorflow as tf #importing installed tensorflow libery as tf
import numpy as np #importing numpy libery as np
with tf.compat.v1.Session() as sess: #opening a session
  a=tf.Variable(0,name='input') #creating an input variable as 'a'
  b=tf.constant(1)# creating a constant variable as 'b'

  mid=tf.add(a,b) # adding a and b variables as labeling it as "mid".
  final=tf.compat.v1.assign(a,mid) # assigning the 'a' and 'mid' to the session

  var=tf.compat.v1.initialize_all_variables() #Installing variables given above
  sess.run(var) # Runnning the session of 'var'
  print(sess.run(a)) #Running the session of 'a'
  for i in range(3): # repeating three times 
    sess.run(final) # running the final session
    print(sess.run(a)) #running session 'a'

Instructions for updating:
Use `tf.global_variables_initializer` instead.


0
1
2
3


In [3]:
import tensorflow as tf #importing tensorflow libery as tf

In [4]:
x=tf.constant(4.) #making 'x' as constant 4
x #displaying 'x'

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [5]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32) #making 'x' constant 4 and giving 1,1 shape which has a float32 data type
x #displaying x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [6]:
x=tf.constant([[2,3,4],[4,5,6]]) # making a matrix with the given lists of numbers.
x  # displaying x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [7]:
tf.ones((3,3)) # making a matrix consists of 1 and has 3,3 size

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
tf.zeros((4,4)) # making a matrix consists of 0 and has 4,4 size

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [9]:
tf.eye(3) # mking a diagnal of 1 in a 3,3 size matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [10]:
tf.eye(7)# mking a diagnal of 1 in a 3,3 size matrix

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [11]:
tf.range(9) #making a list of numbers in a range 9

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [12]:
x=tf.constant([1,2,3]) #enabling x as a list of numbers
y=tf.constant([9,8,7]) #enabling y as a list of numbers
x+y #adding
tf.add(x,y) #adding with tf

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [13]:
tf.subtract(x,y) #substracting with tf
x-y#simple substracting

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [14]:
tf.divide(x,y)#dividing with tf
x/y #dividing simply

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [15]:
tf.multiply(x,y) #Multiplying with tf

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [16]:
x**5 #the power of x 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>